#!/bin/sh

if [ "$1" = "" ] || [ "$2" = "" ]; then
	echo "Specify the input text file, dummy\nUSAGE: ottation TEXT_FILE FILENAME "
	exit 0
fi

if [ ! -d "$HOME/.config/Ottation" ] || [ ! -f "$HOME/.config/Ottation/docStyle.css" ]; then
	echo "No ottation config found... creating"
	mkdir $HOME/.config/Ottation
	touch $HOME/.config/Ottation/docStyle.css
	exit 0
fi
if [ ! -d "$HOME/.local/share/Ottation" ]; then
	echo "Ottation database does not exist... creating"
	mkdir -p $HOME/.local/share/Ottation/documents
	mkdir $HOME/.local/share/Ottation/style
	mkdir $HOME/.local/share/Ottation/images
fi

cp $HOME/.config/Ottation/docStyle.css $HOME/.local/share/Ottation/style/docStyle.css

textOpened=0
pOpened=0

while IFS= read -r line; do
	line=$(echo "$line" | sed 's/	//g')
	if [ $pOpened = 0 ]; then 
		if [ $textOpened = 0 ]; then
			case "$line" in
				\#*)
					TITLE=$(echo "$line" | sed 's/^#//g')
					HEAD="<head>\n	<meta charset=\"utf-8\">\n	<link type=\"text/css\" rel=\"stylesheet\" href=\"../style/docStyle.css\">\n	<title>$TITLE</title>\n</head>"
					echo "$HEAD"
				;;
				\<\#*)
					if [ $textOpened = 0 ]; then
						TEXT=$(echo "$line" | sed 's/^<#//g')
						echo "$TEXT"
						textOpened=1
					fi
				;;
				!*)
					echo "Ignoring Comment: $(echo "$line" | sed 's/^!//g')"
				;;
				*)
				;;
			esac
		else
			case "$line" in
				\>-*)
					preparedLine=$(echo "$line" | sed 's/^>-//g')
					preparedLine="<h1>$preparedLine</h1>"
					TEXT=$(echo "$TEXT\n	$preparedLine")
				;;
				!-*)
					preparedLine=$(echo "$line" | sed 's/^!-//g')
					preparedLine="<h4>$preparedLine</h4>"
					TEXT=$(echo "$TEXT\n	$preparedLine")
				;;
				\>\#*)

				;;
				x-*)
					preparedLine=$(echo "$line" | sed 's/^x-//g')
					preparedLine="<div class=\"list-item\">$preparedLine</div>"
					TEXT=$(echo "$TEXT\n	$preparedLine")
				;;
				*)
					if [ $pOpened = 0 ]; then
						preparedLine="<p>\n		$line"
						pOpened=1
					fi
					TEXT=$(echo "$TEXT\n	$preparedLine")
				;;
			esac
		fi
	else
		case "$line" in
			\>-*)
				preparedLine=$(echo "$line" | sed 's/^>-//g')
				preparedLine="</p>\n	<h1>$preparedLine</h1>"
				TEXT=$(echo "$TEXT\n	$preparedLine")
			;;
			!-*)
				preparedLine=$(echo "$line" | sed 's/^!-//g')
				preparedLine="</p>\n	<h4>$preparedLine</h4>"
				TEXT=$(echo "$TEXT\n	$preparedLine")
				pOpened=0
			;;
			x-*)
				preparedLine=$(echo "$line" | sed 's/^x-//g')
				preparedLine="</p>\n	<div class=\"list-item\">$preparedLine</div>"
				TEXT=$(echo "$TEXT\n	$preparedLine")
				pOpened=0
			;;
			\>\#*)
				preparedLine=$(echo "$line" | sed 's/^>#//g')
				preparedLine="</p>\n$preparedLine"
				TEXT=$(echo "$TEXT\n	$preparedLine")
				pOpened=0
			;;
			*)
				TEXT=$(echo "$TEXT\n	$line")
			;;
		esac
	fi
done < "$1"
BODY="<body>\n	$TEXT\n	\n</body>"
echo $BODY

echo "$HEAD" > "$HOME/.local/share/Ottation/documents/$2"
echo "$BODY" >> "$HOME/.local/share/Ottation/documents/$2"
